# general settings
name: MyArch_x2_c60b24h3
model_type: MyModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0
# auto_resume

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K_train_HR
    dataroot_lq: datasets/DIV2K_train_LR_bicubic/X2
    meta_info_file: ~
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 100
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Set5/HR
    dataroot_lq: datasets/Set5/LR_bicubic/X2
    io_backend:
      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/Set14/HR
    dataroot_lq: datasets/Set14/LR_bicubic/X2
    io_backend:
      type: disk
  val_3:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: datasets/Urban100/HR
    dataroot_lq: datasets/Urban100/LR_bicubic/X2
    io_backend:
      type: disk
  val_4:
    name: B100
    type: PairedImageDataset
    dataroot_gt: datasets/B100/HR
    dataroot_lq: datasets/B100/LR_bicubic/X2
    io_backend:
      type: disk
  val_5:
    name: Manga109
    type: PairedImageDataset
    dataroot_gt: datasets/Manga109/HR
    dataroot_lq: datasets/Manga109/LR_bicubic/X2
    io_backend:
      type: disk



# network structures
network_g:
  type: MyArch
  upscale: 2
  num_feat: 64
  num_block: 24
  num_in_ch: 3
  num_out_ch: 3
  act: 'relu'
  img_range: 255.
  rgb_mean: [0.4488, 0.4371, 0.4040]
# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~
  visualization: results

# training settings
train:
  ema_decay: 0.999
  test_only: false
  test_own: ~

  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]


  scheduler:
    type: MultiStepLR
    milestones: [125000, 200000, 250000]
    gamma: 0.5


  total_iter: 300000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  test_only: true
  test_own: ~
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher



# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
